atm9使用GTMT错误
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.GlobalPos.m_122640_()" because the return value of "com.hepdd.gtmthings.api.misc.WirelessEnergyContainer.getBindPos()" is null